### PR TITLE
Update from upstream for big sur support

### PR DESCRIPTION
**Pull request by adamf**
update to latest from upstream for big sur support

### CODE REVIEW

**Comment by jmo-qap** [comment]
What was your testing method for this? Did you uninstall all of brew, delete all packages and reinstall it?

Also, I'm particularly interested in the changes to `Library/Homebrew/brew.sh` and `Library/Homebrew/update.sh`

**Comment by jmo-qap** [comment]
This PR should be accompanied with bringing brew-install up to date: https://github.com/bitdotioinc/brew-install/compare/master...Homebrew:master

**Comment by adamf** [comment]
> This PR should be accompanied with bringing brew-install up to date: [bitdotioinc/brew-install@master...Homebrew:master](https://github.com/bitdotioinc/brew-install/compare/master...Homebrew:master)

Yep, done.

**Comment by adamf** [comment]
> What was your testing method for this? Did you uninstall all of brew, delete all packages and reinstall it?
> 
> Also, I'm particularly interested in the changes to `Library/Homebrew/brew.sh` and `Library/Homebrew/update.sh`

Yep - brew.sh still refers to our location, and I tested by removing all brew and it's folders, installed master, ran install_core_tools/etc, and ran our software - this on both catalina and big sur..

**Review by jmo-qap — APPROVED** [review]

**Pull request merged**
